name: py2k7theano
dependencies:
- openssl=1.0.2j=0
- pip=9.0.1=py27_0
- python=2.7.12=1
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - bitsets==0.7.10
  - concepts==0.7.10
  - cycler==0.10.0
  - graphviz==0.5.1
  - matplotlib==1.5.3
  - numpy==1.11.2
  - pyparsing==2.1.10
  - python-dateutil==2.6.0
  - python-speech-features==0.4
  - pytz==2016.7
##  - scikits.audiolab==0.11.0
  - scipy==0.18.1
  - six==1.10.0
  - theano==0.7.0
